version: '3'

services:
  # 后端API服务
  api:
    build: .
    image: calendar-app-backend
    container_name: calendar-app-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/calendar-app
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=5000000
      - CORS_ORIGIN=*
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo

  # MongoDB数据库
  mongo:
    image: mongo:5
    container_name: calendar-app-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
